/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/b6Xgn1l7VhW
 */
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@/components/ui/accordion"

export function Equipe() {
    return (
        <div className="bg-white">
            <main className='flex flex-col gap-8 w-full md:w-[700px]'>
                <section>
                    <div className="flex gap-2 mb-2">
                        <img
                            alt="École"
                            height="200"
                            src="/placeholder.svg"
                            style={{
                                aspectRatio: "1/1",
                                objectFit: "cover",
                            }}
                            width="200"
                        />
                        <div className="flex flex-col gap-5">
                            <h2 className="text-3xl font-bold mb-4">Equipe</h2>
                            <p className="mb-4">
                                L’école primaire Saint-Luc compte sur une équipe école passionnée et à l’écoute des besoins des élèves. Tous ont leur métier à cœur et aident vos enfants à cheminer vers les prochaines étapes de leur développement.
                            </p>
                        </div>
                    </div>
                    <article className="bg-gray-50 text-gray-600 p-4">
                        <Accordion className="w-full" collapsible type="single" defaultValue="item-0">
                            <AccordionItem value="item-0">
                                <AccordionTrigger>Équipe administrative</AccordionTrigger>
                                <AccordionContent>
                                    <div>
                                        <div className="wpb_wrapper">
                                            <p><strong>Directrice</strong> : <a className="text-blue-600" href="mailto: direction.saint-luc@csmb.qc.ca">Catherine Touchette</a></p>
                                            <p><strong>Directrice adjointe</strong> :&nbsp; <a className="text-blue-600" href="mailto: direction.saint-luc@csmb.qc.ca">Rania Altiné</a></p>
                                            <p><strong>Secrétaire</strong> : Nanan Ndri Rose Jeanne Yao<br />
                                                <strong>Agente de bureau</strong>: Hélène Lanteigne</p>
                                            <p><strong>Concierge de jour</strong>: Martin Mailhot<br />
                                                <strong>Concierge de soir</strong>: Frédéric Gagnon</p>
                                            <p><strong>Technicienne du service de garde</strong> : <a className="text-blue-600" href="mailto: lena.beland2@csmb.qc.ca">Léna Béland</a></p>
                                            <p><strong>Bibliothécaire</strong>: Carole Roy</p>
                                        </div>
                                    </div>
                                </AccordionContent>
                            </AccordionItem>
                            <AccordionItem value="item-1">
                                <AccordionTrigger>Équipe d'enseignants</AccordionTrigger>
                                <AccordionContent><div className="wpb_text_column wpb_content_element ">
                                    <div className="wpb_wrapper">
                                        <p><strong>Préscolaire</strong></p>
                                        <p>901: Isabel Savard<br />
                                            010: Amélie Lévesque</p>
                                        <p><strong>Premier cycle</strong></p>
                                        <p>101: Michèle Delisle<br />
                                            102: Théodora Ntiranyibagira<br />
                                            103: Sally Zaki<br />
                                            201: Saydé El Gemayel (Julie Rémillard-Bélanger :&nbsp; jeudi)<br />
                                            202: Mouna Benzeghiba (<em>en remplacement de Stéphanie Vachon</em>)<br />
                                            203: Zoé Lacharité</p>
                                        <p><strong>Deuxième cycle</strong></p>
                                        <p>301: Carole Arscott (Claire Arnaud : jeudi et vendredi)<br />
                                            302: Hélène Bourdeau (Julie Rémillard-Bélanger : vendredi)</p>
                                        <p>303 : Edith Ettieh Epse Amani Amoin (<em>en remplacement de Christine Lapierre</em>)<br />
                                            401: Patricia Lemay<br />
                                            402: Marie-Jacques Étienne</p>
                                        <p><strong>Troisième cycle</strong></p>
                                        <p>501: Mouna Ezzine<br />
                                            502: Julie Sylvestre<br />
                                            591-691: Nicolas Lefebvre<br />
                                            601: Jennifer Rouette (<em>en remplacement de Catherine Jacquaz</em>)<br />
                                            602: Sylvie Dion</p>
                                        <p><strong>Classes de langage</strong></p>
                                        <p>850: Geneviève Gauthier (Claire Arnaud : mercredi)<br />
                                            851: Emilie Gobeil<br />
                                            852: Catherine Gingras</p>
                                        <p><strong>Spécialistes</strong></p>
                                        <p>Anglais: Rebecca-Ann Belmonte (lundi, mardi, jeudi et vendredi)<br />
                                            Anglais: Neven Hames (mardi)<br />
                                            Arts plastiques : Svetlana Crudu Plamadeala (mercredi et vendredi)<br />
                                            Éducation physique: Nicolae Boceanu<br />
                                            Éducation physique: Redouane Bouzelata<br />
                                            Musique: David Chartrand<br />
                                            Orthopédagogue: Sophie Brunelle<br />
                                            Orthopédagogue: Rébecca Dumoulin</p>

                                    </div>
                                </div></AccordionContent>
                            </AccordionItem>
                            <AccordionItem value="item-2">
                                <AccordionTrigger>Équipe de professionnels</AccordionTrigger>
                                <AccordionContent>
                                    TES: Julie Barette<br />
                                    TES: Lise-Anne Dion<br />
                                    TES: Anik Fournelle<br />
                                    TES: Martine Moïse (<em>en remplacement de Maya Lajeunesse</em>)<br />
                                    Psychologue: Natalie Lavallée (mardi et vendredi)<br />
                                    Orthophoniste: Sarita Salameh (lundi au jeudi)<br />
                                    Psychoéducatrice: Annie Routhier (mercredi et jeudi)<br />
                                    Infirmière: Annie-Claude Brunet<br />
                                    Hygiéniste dentaire: Nathalie Bélec
                                </AccordionContent>
                            </AccordionItem>
                            <AccordionItem value="item-3">
                                <AccordionTrigger>Personnel du SDG</AccordionTrigger>
                                <AccordionContent><div className="wpb_wrapper">
                                    <p><strong>Technicienne</strong> : Léna Béland</p>
                                    <p><strong>Éducatrices :</strong></p>
                                    <p>Naima Merabet</p>
                                    <p>Houria Houat</p>
                                    <p>Lynda Dubé</p>
                                    <p>Carole Bellemare</p>
                                    <p>Karine Gambarean</p>
                                    <p>Sandy Allard</p>
                                    <p>Ghita Rifki</p>
                                    <p>Nadine Bou-Rgeily</p>
                                    <p>Fatima Khazzroun</p>
                                    <p>Mylène Benitah</p>
                                    <p><strong>Surveillant.e.s :&nbsp;</strong></p>
                                    <p>Roula Nakhal</p>
                                    <p>Jean Mayar Désir</p>
                                    <p>Denise Girard</p>
                                    <p>Marie-Line Habra</p>
                                    <p>Ann Gagnon</p>
                                    <p>Alexa Le Gallais</p>
                                    <p>Caroline Chenonceaux</p>
                                    <p>Gabrielle Gagnon</p>
                                    <p>Frédéric Gagnon</p>
                                    <p>Beata Malisova</p>
                                </div></AccordionContent>
                            </AccordionItem>
                        </Accordion>
                    </article>
                </section>
            </main>
        </div>
    )
}
