/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/b6Xgn1l7VhW
 */
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@/components/ui/accordion"

export function Functionemer() {
  return (
    <div className="bg-white">
      <main className='flex flex-col gap-8 w-full md:w-[700px]'>
        <section>
          <div className="flex gap-2 mb-2">
            <img
              alt="École"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "1/1",
                objectFit: "cover",
              }}
              width="200"
            />
            <div className="flex flex-col gap-5">
              <h2 className="text-3xl font-bold mb-4">Fonctionnement</h2>
              <p className="mb-4">
                Voici les règles de fonctionnement de l'école, vous les retrouverez dans l'agenda des élèves et nous vous
                remercions d'avance de les consulter et de les appliquer. Cliquer sur les thèmes pour obtenir le détail.
              </p>
            <h3 className="text-2xl font-semibold">Fonctionnement général de l'école</h3>
            </div>
          </div>
          <article className="bg-gray-50 text-gray-600 p-4">
            <Accordion className="w-full" collapsible type="single">
              <AccordionItem value="item-0">
                <AccordionTrigger>Arrivée à </AccordionTrigger>
                <AccordionContent>
                  <p>
                    Les élèves doivent arriver à l'école à 7h40. La ponctualité est de mise. Puisqu'il n'y a pas de
                    surveillance avant cette heure, les élèves (à l'exception des élèves du service de garde) ne doivent
                    pas se présenter à l'école avant 7h40.
                  </p>
                  <p className="mt-2">Sachez que les élèves doivent être prêts à travailler à 7h50.</p>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-1">
                <AccordionTrigger>Circulation dans l'école</AccordionTrigger>
                <AccordionContent>Details about circulation in the school.</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-2">
                <AccordionTrigger>Tenue vestimentaire</AccordionTrigger>
                <AccordionContent>Details about dress code.</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-3">
                <AccordionTrigger>Absences</AccordionTrigger>
                <AccordionContent>Details about absences.</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-4">
                <AccordionTrigger>Bicyclette</AccordionTrigger>
                <AccordionContent>Details about bicycle rules.</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-5">
                <AccordionTrigger>Carte d'autobus</AccordionTrigger>
                <AccordionContent>Details about bus card.</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-6">
                <AccordionTrigger>Médicaments</AccordionTrigger>
                <AccordionContent>Details about medication.</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-7">
                <AccordionTrigger>Persévérance</AccordionTrigger>
                <AccordionContent>Details about perseverance.</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-8">
                <AccordionTrigger>Récréations</AccordionTrigger>
                <AccordionContent>Details about recreations.</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-9">
                <AccordionTrigger>Sécurité autour de l'école</AccordionTrigger>
                <AccordionContent>Details about school security.</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-10">
                <AccordionTrigger>Sortie des classes</AccordionTrigger>
                <AccordionContent>Details about class exit.</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-11">
                <AccordionTrigger>Voyage</AccordionTrigger>
                <AccordionContent>Details about travel.</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-12">
                <AccordionTrigger>Utilisation du cellulaire et autres appareils mobiles</AccordionTrigger>
                <AccordionContent>Details about the use of mobile devices.</AccordionContent>
              </AccordionItem>
            </Accordion>
          </article>
        </section>
      </main>
    </div>
  )
}
