/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/utcBesNmhlq
 */


export function MotDeBienvenue() {
  return (
    <div className="bg-white">
      <main className='flex flex-col gap-8 w-full md:w-[700px]'>
        <div className="">
          <h2 className="text-3xl font-bold tracking-tight">Mot de bienvenue</h2>
          <h3 className="text-xl font-bold mb-5">Le milieu à Ecole Isoko la Source.</h3>
          <div className="flex gap-2">
            <img
              alt="École"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "1/1",
                objectFit: "cover",
              }}
              width="200"
            />
            <div className="flex flex-col gap-5">
              <p className="font-semibold">
                L'école Isoko la Source a été construite en 2012

      
              </p>
              <p>Elle est située à Rubavu, dans un secteur résidentiel.</p>
              <p>
                L'école Isoko la Source se trouve dans un environnement splendide, propice à l'activité physique sur un terrain de jeu intérieure et un grand terrain de jeu à l'extérieure permettant aux élèves de developer leur capacités physiques au grand air.L'école a été bâti dans un milieu calme, reposant et favorable à l'apprentissage. Le site a été minitieusement choisi pour tout ces atouts.
                . C'est donc dans ce contexte que
                les élèves sont appelés à vivre des expériences diverses sur le plan sportif.
              </p>
            </div>
          </div>
          <p className="mb-4">
            L'équipe-école, qui travaille à la réussite des élèves, est engagée, rigoureuse et soucieuse d'un
            environnement propice à leur épanouissement et d'un enseignement de qualité. Le développement des
            compétences et des connaissances se fait dans la diversité des apprentissages et à travers une multitude de
            projets qui suscitent l'intérêt et la motivation chez l'élève. La valorisation de la langue française
            demeure un souci quotidien pour nos intervenants et nos élèves.
          </p>
          <p className="mb-4">
            L'engagement des parents à travers le conseil d'établissement et dans diverses activités est essentiel pour
            nous et permet d'assurer un milieu de vie animé dans lequel il fait bon évoluer.
          </p>
          <br /><br /><br />
          <p className="text-center">Merci!</p>
        </div>
      </main>
    </div>
  )
}
